FROM php:8.2-apache

# Instalar extensiones necesarias
RUN docker-php-ext-install pdo pdo_mysql

# Instalar Composer
RUN apt-get update && apt-get install -y git unzip zip \
    && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && php -r "unlink('composer-setup.php');"

# Establecer el directorio de trabajo y copiar archivos
WORKDIR /var/www/html
COPY . /var/www/html

# Exponer el puerto 80
EXPOSE 80

# Comando que mantiene Apache activo
CMD ["apache2-foreground"]
