FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

#si tengo dos microservicios flask debo cambiar el puerto para que no haya conflicto
EXPOSE 5000
CMD ["python", "app.py"]
